# Generated by Django 3.2.6 on 2021-08-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210812_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedday',
            old_name='reservations',
            new_name='reservation',
        ),
    ]
